void initUSART1(void);
void putchUSART1(char cx);
void newlineUSART1(void);
void putsUSART1(char *ptr);
uint8_t getchUSART1(void);
void getsUSART1(char *ptr);
void int2ASCII(int ix, char *ptr);
int ASCII2int(char *ptr);
void USART1_puti(int ix); 
int USART1_geti(void);
void USART1_putf(float f, int p);
